/**
 * css3动画类库名，共76个
 * https://daneden.github.io/animate.css/
 * @type {{name: string, infinite: string, hinge: string, flash: string, pulse: string, rubberBand: string, shake: string, headShake: string, swing: string, tada: string, wobble: string, jello: string, bounce: string, bounceIn: string, bounceInDown: string, bounceInUp: string, bounceInLeft: string, bounceInRight: string, bounceOut: string, bounceOutUp: string, bounceOutDown: string, bounceOutLeft: string, bounceOutRight: string, fadeIn: string, fadeInDown: string, fadeInDownBig: string, fadeInLeft: string, fadeInLeftBig: string, fadeInRight: string, fadeInRightBig: string, fadeInUp: string, fadeInUpBig: string, fadeOut: string, fadeOutDown: string, fadeOutDownBig: string, fadeOutLeft: string, fadeOutLeftBig: string, fadeOutRight: string, fadeOutRightBig: string, fadeOutUp: string, fadeOutUpBig: string, flip: string, flipInX: string, flipInY: string, flipOutX: string, flipOutY: string, lightSpeedIn: string, lightSpeedOut: string, rollIn: string, rollOut: string, rotateIn: string, rotateInDownLeft: string, rotateInDownRight: string, rotateInUpLeft: string, rotateInUpRight: string, rotateOut: string, rotateOutDownLeft: string, rotateOutDownRight: string, rotateOutUpLeft: string, rotateOutUpRight: string, zoomIn: string, zoomInDown: string, zoomInLeft: string, zoomInRight: string, zoomInUp: string, zoomOut: string, zoomOutDown: string, zoomOutLeft: string, zoomOutRight: string, zoomOutUp: string, slideInDown: string, slideInLeft: string, slideInRight: string, slideInUp: string, slideOutDown: string, slideOutLeft: string, slideOutRight: string, slideOutUp: string}}
 */
export default {
	name:'animated',
	infinite:'infinite',
	
	hinge:'hinge',
	flash:'flash',
	pulse:'pulse',
	rubberBand:'rubberBand',
	shake:'shake',
	headShake:'headShake',
	swing:'swing',
	tada:'tada',
	wobble:'wobble',
	jello:'jello',
	
	bounce:'bounce',
	bounceIn:'bounceIn',
	bounceInDown:'bounceInDown',
	bounceInUp:'bounceInUp',
	bounceInLeft:'bounceInLeft',
	bounceInRight:'bounceInRight',
	bounceOut:'bounceOut',
	bounceOutUp:'bounceOutUp',
	bounceOutDown:'bounceOutDown',
	bounceOutLeft:'bounceOutLeft',
	bounceOutRight:'bounceOutRight',
	
	fadeIn:'fadeIn',
	fadeInDown:'fadeInDown',
	fadeInDownBig:'fadeInDownBig',
	fadeInLeft:'fadeInLeft',
	fadeInLeftBig:'fadeInLeftBig',
	fadeInRight:'fadeInRight',
	fadeInRightBig:'fadeInRightBig',
	fadeInUp:'fadeInUp',
	fadeInUpBig:'fadeInUpBig',
	fadeOut:'fadeOut',
	fadeOutDown:'fadeOutDown',
	fadeOutDownBig:'fadeOutDownBig',
	fadeOutLeft:'fadeOutLeft',
	fadeOutLeftBig:'fadeOutLeftBig',
	fadeOutRight:'fadeOutRight',
	fadeOutRightBig:'fadeOutRightBig',
	fadeOutUp:'fadeOutUp',
	fadeOutUpBig:'fadeOutUpBig',
	
	flip:'flip',
	flipInX:'flipInX',
	flipInY:'flipInY',
	flipOutX:'flipOutX',
	flipOutY:'flipOutY',
	
	lightSpeedIn:'lightSpeedIn',
	lightSpeedOut:'lightSpeedOut',
	rollIn:'rollIn',
	rollOut:'rollOut',
	
	rotateIn:'rotateIn',
	rotateInDownLeft:'rotateInDownLeft',
	rotateInDownRight:'rotateInDownRight',
	rotateInUpLeft:'rotateInUpLeft',
	rotateInUpRight:'rotateInUpRight',
	rotateOut:'rotateOut',
	rotateOutDownLeft:'rotateOutDownLeft',
	rotateOutDownRight:'rotateOutDownRight',
	rotateOutUpLeft:'rotateOutUpLeft',
	rotateOutUpRight:'rotateOutUpRight',
	
	zoomIn:'zoomIn',
	zoomInDown:'zoomInDown',
	zoomInLeft:'zoomInLeft',
	zoomInRight:'zoomInRight',
	zoomInUp:'zoomInUp',
	zoomOut:'zoomOut',
	zoomOutDown:'zoomOutDown',
	zoomOutLeft:'zoomOutLeft',
	zoomOutRight:'zoomOutRight',
	zoomOutUp:'zoomOutUp',
	
	slideInDown:'slideInDown',
	slideInLeft:'slideInLeft',
	slideInRight:'slideInRight',
	slideInUp:'slideInUp',
	slideOutDown:'slideOutDown',
	slideOutLeft:'slideOutLeft',
	slideOutRight:'slideOutRight',
	slideOutUp:'slideOutUp'
};